#+STARTUP: overview

* 知识那么多, 我们应该怎么做

  1. 极致的事情必定是简单的
     以一个事情为基点 然后去专供一件事情
     最简单的比如以mac系统为起点, 去实现自己想做的事情

     说白了就是熟悉命令行, 然后去完成一系列事情. mac只是一个起点, 最重要的还是后面要处理的事情。

     mac --> 熟悉的系统, 对事情的效率有非常大的提高
     git --> 版本管理, 方便自己随时回退
     gitlab --> 团队管理， 非个人使用
     hexo --> 博客记录，博客只是作为记录使用, 无法真正做到梳理知识体系

     以mac为基础, git, hexo辅助, 去完成一些事情. 
     真正的目标, 比如黑客, 比如赚钱的项目.  相信技术是可以赚钱的, 没有赚钱只是说明技术还没有到位

  2. 心态决定道路
     没有好的心态, 很难走下去
     
     荣辱不惊. 得意时不洋洋得意, 失意时不落落寡欢

* autotools实际使用
  1. 发布时候 提供./configure目录之前的东西即可
  2. 文件夹准备
     include -- 放置头文件
     src     -- 放置源文件

** 疑问
   1. autoscan生成的.scan文件中AC_INIT和AM_INIT_AUTOMAKE的具体差异

   2. 完成ya-snippt的整理

   3. 子目录Makefile.am
      如果子目录下Makefile.am目标为lib, 则automake可以正常通过,  ./configure也可以正常运行. 
      前提是依赖于root/configure.am中需要添加该宏指令: AC_PROG_RANLIB（生成静态库）

      如果子目录下Makefile.am目标为program, 则automake可以正常运行, 但是子目录下并没有生成Makefile.in.暂时还不知道问题在哪

   4. 返回指针 还是返回引用
   
** 记录
   1. std::string本身没有格式化的函数, 使用的是sprintf
      printf  将目标格式化 并输出到标准输出
      sprintf 将目标格式化 并输出到目标变量中
   2. c++ 纯虚函数 是=0
      virtual void Display () = 0; // 纯虚函数
      最后面的“=0”并不表示函数返回值为0，它只起形式上的作用，告诉编译系统“这是虚函数”
   3. extern void *memset(void *buffer, int c, int count)        
      buffer：为指针或是数组,
      c：是赋给buffer的值,
      count：是buffer的长度.

      count不能使用sizeof运算符, sizeof求的是内存中的字节数(char数目)
   4. c++ there are no arguments to 'memset' that depend on a template parameter
      #+BEGIN_EXAMPLE
      template  class ComboMill
      {
      // ...
	
      void SetMembership (bool iIsMember)
      {
           for (int i = 0; i < mMembership.size(); i++)
		{
			mMembership[i] = iIsMember;
		}
	}
	
	void First ()
	{
		// error on next line
		SetMembership (false);
	}
 
	// ...
	};
      #+END_EXAMPLE
      代码如上, g++编译的时候回报如上的错误, 提示对于模板类, 该函数错误
      修改的话,如下. 但是还不知道原因
      #+BEGIN_EXAMPLE
      	void First ()
	{
		// error on next line
		this->SetMembership (false);
	}
 
	// ...
	};
      #+END_EXAMPLE
   5. char 与 wchar_t
      | 类型    | 说明          | 求字符长 | 求内存长 | 备注 |
      |---------+---------------+----------+----------+------|
      | char    | 单字节        | strlen   | sizeof   |      |
      |---------+---------------+----------+----------+------|
      | wchar_t | 扩展字符      | wcslen   | sizeof   |      |
      |         | 多用于unicode |          |          |      |
      |---------+---------------+----------+----------+------|3
   6. dllimport 与 dllexport
      

* 91秘密  
发布器将不再使用，请使用以下方法。
91porn永久地址: 91porn.com
请把这页内容复制到你的记事本上或妥善保存在其他地方比如有道云笔记,以免找不到我们!
凡是需要先买VIP，和注册账号才能看的都是假网站！

最佳办法，翻墙后访问 91porn.com，通常，在首页上有最新可以用的地址 
目前的频率是每20天换一次域名。
方法1：
91porn防屏蔽地址： （对于导航站的站长，这个特别有用，这样您的网站上的地址就不用更改了，只要官方一更新，您永远有最新的地址了，可以一劳永逸！）
http://jonsnow.club
http://91dizhi.rocks
http://91porn.news

http://mygameofthrones.space/Cazn2  




方法2：
备用地址：

http://www.ebay.com/usr/91dizhi_1

方法3：
如果因各种原因，以上方法都不行，可以发送邮件到 91dizhi#gmail.com  # 换成 @ ，索取最新地址。

* 我为什么值每月2万
** 个人
   1. 已掌握的技能
      1) C++
      2) linux && mac
	 1) 曾在linux(服务器版本, 非gui)下搭建过各种服务器 vsftp, git, gitois, gitweb, gitlab等
	 2) 后将gitlab转移到mac pro上, 并做长期维护
	 3) 长期在mac pro上工作, 对于各种特性比较熟悉
      3) git
	 1) git官方文档完整阅读过一遍, git使用多年, 多次进行git培训
	 2) 多次搭建并维护git服务器. 详见1-2
	 3) 常年混迹github. 
      4) shell脚本
	 几个实用脚本
	 1) ios一键打包脚本
	 2) git自动同步脚本
	 3) vs一键打包脚本
      5) emacs
	 emacs 5年使用经验
	 熟练使用GTD知识管理工具org
	 熟悉并爱钻研emacs本身及插件特性. 喜欢读elisp源码
      6) 个人博客hexo
	 正在将emacs的GTD中部分内容慢慢转移到hexo
   2. 掌握但不算熟悉的技能
      1) u3d
      2) java  了解android studio
      3) ios
      4) u3d 与 java 互相交互
      5) u3d 接入各种sdk
   3. 个人评价
      1) 学习能力强, 能快速学习新知识新环境
      2) 有钻研精神, 热爱技术
      3) 吃苦耐劳, 有毅力, 不会轻易放弃

** 团队
   1. 做过的事情
      1) 参与过华为的小组团队
	 华为终端底层系统
      2) 带领过40多人的大团队
	 棋牌项目
      3) 带领过10人的小团队
	 棋牌项目
   2. 与客户有长久接触
      能挖掘客户真实意图, 避免很多沟通上的麻烦
   3. 有团队管理经验, 工作管理上凌厉, 私下懂得处理好人际关系

** 公司
   1. 大学有过2年创业经验
   2. 毕业后, 17年创业至今, 懂得站在公司角度去看待事物.
   3. 懂得感恩, 不会抱怨

** 期望
   最好从事棋牌行业或者游戏行业,
   能在公司中实现自我价值, 财务自由

** 总结
   1. 优点
      能专心做事, 做事也负责. 对于学习新事物只会兴奋, 不会觉得是压力.
      与同事, 客户沟通交流没有障碍, 能很好的处理各种人际关系.
      不怕风险
   2. 缺点
      对于事物太过专注, 当长期没有进展的时候, 会进入到自我怀疑状态, 导致状态不对. 在自我调整方面需要改进.


* bili


  | 账号        | 密码        | 英雄                           | 礼装              |
  |-------------+-------------+--------------------------------+-------------------|
  | h2908400254 | 75806768    | 黑贞德, 孔明, 梅林, 神秘女主角 | 2030(3个)  万华镜 |
  |-------------+-------------+--------------------------------+-------------------|
  | r0037469755 | b5e47735    | 黑贞德, 神秘女主角(5宝)        | 2030(4个)         |
  |-------------+-------------+--------------------------------+-------------------|
  | snowysprin  | Wx501031219 |                                |                   |
  |-------------+-------------+--------------------------------+-------------------|
  
  

  
